"""Puertos requeridos por los casos de uso de edicion."""

from __future__ import annotations

from typing import Protocol

from clipperkick.domain.edit.history import Draft, EditRevision, Variant


class RepositorioEdicion(Protocol):
    def crear_borrador(self, draft: Draft, variant: Variant, revision: EditRevision) -> None: ...
    def obtener_draft(self, draft_id: str) -> Draft: ...
    def obtener_variant(self, variant_id: str) -> Variant: ...
    def obtener_revision(self, revision_id: str) -> EditRevision: ...
    def confirmar_revision(
        self, variant_id: str, expected_revision_id: str, revision: EditRevision,
    ) -> Variant: ...
    def mover_puntero(
        self, variant_id: str, expected_revision_id: str, target_revision_id: str,
    ) -> Variant: ...
    def duplicar_variant(self, variant: Variant,
                         fork_revision: EditRevision | None = None) -> None: ...
    def hijos(self, revision_id: str, variant_id: str) -> tuple[EditRevision, ...]: ...
    def historial(self, variant_id: str) -> tuple[EditRevision, ...]: ...
    def revision_inicial(self, draft_id: str) -> EditRevision: ...


__all__ = ["RepositorioEdicion"]
